#!/bin/bash
OPTS="h"

#
# helpers
#

function print_info() {
    printf ":: %s\n" "$@"
}

function print_error() {
    printf "Error: %s\n" "$@"
}

function exit_error() {
    print_error "$@"
    exit 1
}

function help() {
cat <<EOF
    usage: $(basename $0) [-h]

    Description

    Options:
      -h         Print this help.
EOF
}

#
# Main
#

while getopts $OPTS OPTION
do
  case $OPTION in
    h)
        help
        exit
        ;;
  esac
done

[ ! -e "Makefile" ] && exit_error "Makefile not found, are you in the test dir?"
[ ! -e "runtest.sh" -a ! -e "lib.sh" ] && exit_error "runtest.sh or lib.sh not found, are you in the test dir?"

# replacement
if [ -e "Makefile" ]; then
  print_info "include /usr/share/rhts/lib/rhts-make.include -> make optional"
  sed -ri 's/^(include.*rhts-make\.include.*)/-\1/' Makefile
fi

if [ -e "runtest.sh" ]; then
  print_info "remove sourcing of /usr/bin/rhts-environment.sh"
  sed -ri 's/^(\.|source) \/usr\/bin\/rhts-environment\.sh.*/\[ -e \/usr\/bin\/rhts-environment\.sh \] \&\& \. \/usr\/bin\/rhts-environment\.sh/' runtest.sh
fi

# warnings - inappropriate content

# vim: ts=4 sw=4 sts=4 ft=sh et ai:
