#!/bin/bash
#
# This script resolves dependencies of the given beakerlib test and clones
# required libraries' git repositories from GIT_BASE_URL to directory
# specified by the BEAKER_LIBRARY_PATH. After the script finishes, it prints
# two lines, with space delimited list of components from RhtsRequires
# and Requires.
#
# Authors:
#  Jakub Heger <jheger@redhat.com>
#  Martin Kyral <mkyral@redhat.com>
#  Miroslav Vadkerti <mvadkert@redhat.com>
#

# TODO: note that we will need to have multiple GIT_BASE_URLs in the future
[ -z "$GIT_BASE_URL" ] && GIT_BASE_URL="https://upstreamfirst.fedorainfracloud.org/COMPONENT.git"
[ -z "$BEAKERLIB_LIBRARY_PATH" ] && BEAKERLIB_LIBRARY_PATH="/mnt/libraries"

# options
OPTS="h"

#
# helpers
#

function print_info() {
    printf ":: %s\n" "$@"
}

function print_error() {
    printf "Error: %s\n" "$@"
}

function exit_error() {
    print_error "$@"
    exit 1
}

function help() {
cat <<EOF
    usage: $(basename $0) [-h]

    Description

    Options:
      -h         Print this help.
EOF
}

#
# Main
#

while getopts $OPTS OPTION
do
  case $OPTION in
    h)
        help
        exit
        ;;
  esac
done

TEST=$1
[ -z "$TEST" ] && exit_error "No test specified"
[ -f $TEST/Makefile ] || exit_error "Makefile not found @ $TEST/Makefile"

REQUIRES_DEPS=
RHTSREQUIRES_DEPS=
PROCESSED_LIBS=

#
# Process a beakerlib library and recursively resolve it's dependencies.
#
# Params:
# $1 - library name - e.g. httpd/http
#
function process_library() {
   # skip already processed beakerlib libraries
   grep -q "$1" <<< "$PROCESSED_LIBS" && return
   PROCESSED_LIBS="$PROCESSED_LIBS $1"

   COMPONENT=${1///*}
   LIBRARY=${1##*/}
   GIT_REPO_BASE="$GIT_BASE_URL/$COMPONENT"

   # clone git repository if it does not exist
   if [ ! -d $BEAKERLIB_LIBRARY_PATH/$COMPONENT ]; then
     git clone ${GIT_REPO_BASE} $BEAKERLIB_LIBRARY_PATH/$COMPONENT 1>&2 || \
       exit_error "Could not clone $GIT_REPO_BASE to $BEAKERLIB_LIBRARY_PATH/$COMPONENT"
   fi

   resolve_deps ${BEAKERLIB_LIBRARY_PATH}/$COMPONENT/Library/$LIBRARY
}

#
# Recursively resolves test dependencies of beakerlib test specified with a path.
#
# Params:
# $1 - path to a beakerlib test
#
function resolve_deps() {
  local REQUIRES=$(sed -n 's/.*\"Requires:[[:space:]]*\(.*\)".*/\1/p' $1/Makefile)
  local RHTSREQUIRES=$(sed -n 's/.*RhtsRequires:[[:space:]]*\(.*\)".*/\1/p' $1/Makefile)
  # sed -n 's/.*Requires:[[:space:]]*\(.*\)".*/\1/p' $1/Makefile

  for REQ in $REQUIRES; do
    if egrep -qv '^\$\(' <<< $REQ; then
      REQUIRES_DEPS="$REQUIRES_DEPS $REQ"
    fi
  done

  for RHTSREQ in $RHTSREQUIRES; do
    if egrep -q "^library\(" <<< $RHTSREQ; then
      process_library $(sed 's/library(\(.*\))/\1/' <<< $RHTSREQ)
    elif egrep -qv '^\$\(' <<< $RHTSREQ; then
      RHTSREQUIRES_DEPS="$RHTSREQUIRES_DEPS $RHTSREQ"
    fi
  done
}

resolve_deps $TEST

echo "$RHTSREQUIRES_DEPS" | xargs -n1 | sort | uniq | xargs
echo "$REQUIRES_DEPS" | xargs -n1 | sort | uniq | xargs

# vim: ts=4 sw=4 sts=4 ft=sh et ai:
